# Generated by Django 3.2 on 2021-04-11 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olamides_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 11, 30, 17, 615152)),
        ),
    ]
